Doppel content pack
metron-labs/content pull request #9
Opened 2024-12-10 14:54 UTC by kapil-metron

Implementation for the command get-alert and it's unit tests

2024-12-11 16:23 UTC, devang-metron requested changes
Fix the pack readme and liniting errors.

2024-12-11 16:23 UTC, devang-metron commented on Packs/Doppel/Integrations/Doppel/Doppel.py
> +        api_url = f"{self._base_url}/{api_name}?"
use params instead of adding it in the string itself

2024-12-12 08:16 UTC, anuj-metron approved these changes

2024-12-12 08:17 UTC, anuj-metron approved these changes

2024-12-12 08:17 UTC, anuj-metron approved these changes

2024-12-12 08:19 UTC, anuj-metron approved these changes

2024-12-12 08:24 UTC, anuj-metron approved these changes

2024-12-12 08:25 UTC, anuj-metron approved these changes

2024-12-12 08:25 UTC, anuj-metron approved these changes

2024-12-12 08:26 UTC, anuj-metron approved these changes

2024-12-12 09:32 UTC, devang-metron approved these changes

2024-12-12 10:15 UTC, merged